# ============================================
# CONFIGURACION DE SPRING BOOT
# ============================================

# 1. Configuracion de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/citas_medicas
spring.datasource.username=postgres
spring.datasource.password=12345678Bony

# 2. Configuracion de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# 3. Logging (para ver las consultas SQL)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# 4. Configuracion del servidor
server.port=8081
spring.main.allow-circular-references=true
